version: 0.2

env:
  variables:
    ImageName: "react-vite-shadcn"

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 627216615313.dkr.ecr.us-east-1.amazonaws.com
      - echo "Files in project:"
      - ls -la

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ImageName:latest .

  post_build:
    commands:
      - echo "Tagging and pushing..."
      - docker tag $ImageName:latest 627216615313.dkr.ecr.us-east-1.amazonaws.com/$ImageName:latest
      - docker push 627216615313.dkr.ecr.us-east-1.amazonaws.com/$ImageName:latest
      - echo "Done!"
